### ISSUE TITLE
npx tsc; node ./dist/cli/getSprints.js PrjKeyを実行したときにimport errorが発生する

### ISSUE THREAD

**Issue by pa-s-fukuda** [pa-k-sato/jira-task-register#1]
## 課題
`npx tsc; node ./dist/cli/getSprints.js PrjKey`を叩いた際にエラーが発生する

## 原因
`getSprints.ts`が読み込んでいる`import { GetSprintsUsecase } from "../usecases/getSprintsUsecase";`でエラーが出ています
importの記述には`getSprintsUsecase`となっているのですが、実際のファイル名は`GetSprintsUsecase`になっているためエラーが出るみたいです。

**Comment by pa-s-fukuda** [comment]
@pa-k-sato 
こちら確認していただいても良いですか？

**Comment by pa-k-sato** [comment]
@pa-s-fukuda 
ありがとうございます。修正しました。
（PR 作ればよかった。。。）

**Comment by pa-s-fukuda** [comment]
対応ありがとうございます！
こちらcloseします
